#服务端口号
server:
  port: 3333
#别名
spring:
  application:
    name: eureka-server-03

#eureka配置
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:2222/eureka/
